#!/usr/bin/env python3
"""
gen_trust_anchors.py — Generate BearSSL trust anchor C header from PEM CA bundle.

Reads a PEM file containing root CA certificates (e.g. /etc/ssl/certs/ca-certificates.crt)
and outputs a C header with statically-initialized br_x509_trust_anchor arrays ready for
BearSSL's br_x509_minimal validator.

Usage:
    python3 tools/gen_trust_anchors.py /etc/ssl/certs/ca-certificates.crt \
        > src/user/apps/ts_trust_anchors.h

Requires: pip install cryptography
"""

import sys
import datetime
from cryptography import x509
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric import rsa, ec, ed25519, ed448

# BearSSL curve constants (from bearssl_ec.h)
BEARSSL_CURVES = {
    "secp256r1": 23,  # BR_EC_secp256r1
    "secp384r1": 24,  # BR_EC_secp384r1
    "secp521r1": 25,  # BR_EC_secp521r1
}


def format_c_bytes(data, indent=4):
    """Format a byte sequence as a C array initializer."""
    hex_strs = [f"0x{b:02X}" for b in data]
    lines = []
    per_line = 12
    for i in range(0, len(hex_strs), per_line):
        chunk = ", ".join(hex_strs[i:i + per_line])
        if i + per_line < len(hex_strs):
            chunk += ","
        lines.append(" " * indent + chunk)
    return "\n".join(lines)


def extract_cert_data(cert):
    """Extract DN (DER) and public key from an X.509 certificate.
    Returns (dn_der, key_info) or (None, None) on unsupported key type."""
    dn_der = cert.subject.public_bytes()
    pub_key = cert.public_key()

    if isinstance(pub_key, rsa.RSAPublicKey):
        numbers = pub_key.public_numbers()
        n_bytes = numbers.n.to_bytes((numbers.n.bit_length() + 7) // 8, "big")
        e_bytes = numbers.e.to_bytes((numbers.e.bit_length() + 7) // 8, "big")
        return dn_der, {"type": "rsa", "n": n_bytes, "e": e_bytes}

    elif isinstance(pub_key, ec.EllipticCurvePublicKey):
        q_bytes = pub_key.public_bytes(
            serialization.Encoding.X962,
            serialization.PublicFormat.UncompressedPoint,
        )
        curve_name = pub_key.curve.name
        if curve_name not in BEARSSL_CURVES:
            return None, None
        return dn_der, {
            "type": "ec",
            "q": q_bytes,
            "curve_id": BEARSSL_CURVES[curve_name],
        }

    else:
        # Ed25519, Ed448, etc. — not supported by BearSSL
        return None, None


def parse_pem_bundle(path):
    """Parse all certificates from a PEM bundle file."""
    with open(path, "rb") as f:
        pem_data = f.read()

    certs = []
    while b"-----BEGIN CERTIFICATE-----" in pem_data:
        start = pem_data.index(b"-----BEGIN CERTIFICATE-----")
        end = pem_data.index(b"-----END CERTIFICATE-----") + len(
            b"-----END CERTIFICATE-----"
        )
        cert_pem = pem_data[start:end]
        pem_data = pem_data[end:]
        try:
            cert = x509.load_pem_x509_certificate(cert_pem)
            certs.append(cert)
        except Exception as e:
            print(f"/* WARNING: skipped unparseable cert: {e} */", file=sys.stderr)
    return certs


def main():
    if len(sys.argv) < 2:
        print(f"Usage: {sys.argv[0]} <pem-bundle-file>", file=sys.stderr)
        sys.exit(1)

    pem_path = sys.argv[1]
    certs = parse_pem_bundle(pem_path)

    # Extract data from each cert, skip unsupported key types
    anchors = []
    skipped = 0
    for cert in certs:
        dn_der, key_info = extract_cert_data(cert)
        if dn_der is None:
            skipped += 1
            continue
        cn = "unknown"
        try:
            cn_attr = cert.subject.get_attributes_for_oid(x509.oid.NameOID.COMMON_NAME)
            if cn_attr:
                cn = cn_attr[0].value
        except Exception:
            pass
        anchors.append((cn, dn_der, key_info))

    now = datetime.datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")

    # Emit C header
    print(f"""/*
 * ts_trust_anchors.h — Embedded root CA trust anchors for BearSSL
 *
 * AUTO-GENERATED by tools/gen_trust_anchors.py on {now}
 * Source: {pem_path}
 * Anchors: {len(anchors)} ({skipped} skipped — unsupported key types)
 *
 * DO NOT EDIT BY HAND. Regenerate with:
 *   python3 tools/gen_trust_anchors.py {pem_path} > src/user/apps/ts_trust_anchors.h
 */

#ifndef TS_TRUST_ANCHORS_H
#define TS_TRUST_ANCHORS_H

#include "bearssl/inc/bearssl.h"
""")

    # Emit byte arrays for each anchor
    for i, (cn, dn_der, key_info) in enumerate(anchors):
        print(f"/* [{i}] {cn} */")
        print(f"static const unsigned char TA_DN_{i}[] = {{")
        print(format_c_bytes(dn_der))
        print("};")

        if key_info["type"] == "rsa":
            print(f"static const unsigned char TA_RSA_N_{i}[] = {{")
            print(format_c_bytes(key_info["n"]))
            print("};")
            print(f"static const unsigned char TA_RSA_E_{i}[] = {{")
            print(format_c_bytes(key_info["e"]))
            print("};")
        else:
            print(f"static const unsigned char TA_EC_Q_{i}[] = {{")
            print(format_c_bytes(key_info["q"]))
            print("};")
        print()

    # Emit the trust anchor array
    print(f"static const br_x509_trust_anchor TS_TRUST_ANCHORS[] = {{")
    for i, (cn, dn_der, key_info) in enumerate(anchors):
        print(f"    /* [{i}] {cn} */")
        print(f"    {{")
        print(
            f"        {{ (unsigned char *)TA_DN_{i}, sizeof(TA_DN_{i}) }},"
        )
        print(f"        BR_X509_TA_CA,")
        if key_info["type"] == "rsa":
            print(f"        {{")
            print(f"            BR_KEYTYPE_RSA,")
            print(f"            {{ .rsa = {{")
            print(
                f"                (unsigned char *)TA_RSA_N_{i}, sizeof(TA_RSA_N_{i}),"
            )
            print(
                f"                (unsigned char *)TA_RSA_E_{i}, sizeof(TA_RSA_E_{i})"
            )
            print(f"            }} }}")
            print(f"        }}")
        else:
            print(f"        {{")
            print(f"            BR_KEYTYPE_EC,")
            print(f"            {{ .ec = {{")
            print(f"                {key_info['curve_id']},")
            print(
                f"                (unsigned char *)TA_EC_Q_{i}, sizeof(TA_EC_Q_{i})"
            )
            print(f"            }} }}")
            print(f"        }}")
        if i < len(anchors) - 1:
            print(f"    }},")
        else:
            print(f"    }}")
    print("};")
    print()
    print(
        f"#define TS_TRUST_ANCHORS_NUM  "
        f"(sizeof(TS_TRUST_ANCHORS) / sizeof(TS_TRUST_ANCHORS[0]))"
    )
    print()
    print("#endif /* TS_TRUST_ANCHORS_H */")


if __name__ == "__main__":
    main()
